### ISSUE TITLE
Null Error 

### ISSUE THREAD

**Issue by SeniorCluckers** [austinpilz/FridayThe13th#1]
`[17:15:53] [Server thread/ERROR]: Error occurred while enabling FridayThe13th v1.1.2 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:91) ~[spigot.jar:git-Spigot-7228328-14b597f]
	at com.AustinPilz.FridayThe13th.IO.InputOutput.loadChests(InputOutput.java:388) ~[?:?]
	at com.AustinPilz.FridayThe13th.FridayThe13th.onEnable(FridayThe13th.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-7228328-14b597f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by austinpilz** [comment]
It looks like you added a chest and then the chest in that location was deleted or broken. It's attempting to get a block in that location but there isn't one there anymore. 

If the problem persists, delete the db.sqlite file in the Friday the 13th folder and setup the arena again. What SHOULD happen is that it should catch this issue and just delete the chest and proceed normally. I will issue a hot patch later tonight that will address this console issue. Thanks for reporting!

**Comment by SeniorCluckers** [comment]
I can promise you I did not delete any chests. I fixed the issue by return; for now.. But Ill setup the arena again. Are double chests allowed?

**Comment by austinpilz** [comment]
Yes sir, double chests are allowed. Both blocks in a double chest refer to the same block state. 

The world name is stored as a string and are retrieved as a string, so it should save exactly what the API returns when it asks for the worlds name.

**Comment by austinpilz** [comment]
Figured it out! I just looked - the table defined "World" as a double for some reason. That is so strange! The next update will have a fix for this - when it comes out, delete your DB and then reload, it'll make a new DB where "world" for signs and chests is String instead of Double.

So sorry for that mistake! Thanks for your help!
