### ISSUE TITLE
Errors spam in Console. Disable skin?

### ISSUE THREAD

**Issue by Fiks75** [austinpilz/FridayThe13th#10]
Spigot 1.12. Spam errors console. It is possible to disable the skin Jason in config.yml? Errors due to skin Jason.

[23:35:58 WARN]: [FridayThe13th] Task #31 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.prepareForGameplay(Counselor.java:146) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.performInProgressActions(PlayerManager.java:617) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.beginGame(GameManager.java:356) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.changeGameStatus(GameManager.java:338) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.checkGameStatus(GameManager.java:245) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.GameStatusCheck.run(GameStatusCheck.java:17) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:35:58 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:35:58 WARN]: Fiks75 moved too quickly! -75.17637843627614,0.0,-237.41415498284334
[23:35:59 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:36:00 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:36:01 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:36:02 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:36:03 WARN]: [FridayThe13th] Task #38 for FridayThe13th v1.5.1 generated an exception
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:44) ~[?:?]
        at com.AustinPilz.FridayThe13th.Components.Characters.Counselor.updateSkin(Counselor.java:570) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.CounselorStatsDisplayUpdate.run(CounselorStatsDisplayUpdate.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by austinpilz** [comment]
From looking at this, it's not the Jason skin, it's the counselor skins that every player gets. You're unable to disable skins in the game as 1.6 only adds more skins, a huge component of the game.

Are you running Spigot 1.12 or Spigot 1.12_R1?

**Comment by Fiks75** [comment]
[00:21:35 INFO]: This server is running CraftBukkit version git-Spigot-596221b-2c5c611 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[00:21:35 INFO]: Checking version, please wait...
[00:21:37 INFO]: You are running the latest version

**Comment by austinpilz** [comment]
It's designed to only work on Spigot servers, which I believe is equivalent in terms of compatibility to craftbukkit. It's not designed nor supported for pirate servers, unfortunately

**Comment by Fiks75** [comment]
I use Spigot 1.12_R1.

**Comment by austinpilz** [comment]
Huh, then you shouldn't have any issues. The issue doesn't originate from the F13 code, there appears to be an issue with the map in the package that is used by Spigot.

**Comment by Fiks75** [comment]
Version 1.4 F13 good works to Spigot 1.12, but since version 1.4.1 does not work.
