### ISSUE TITLE
Spam console when start with 2 players

### ISSUE THREAD

**Issue by kujinvn147** [austinpilz/FridayThe13th#6]
`[17:48:27] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to FridayThe13th v1.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:616) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.isJason(PlayerManager.java:133) ~[?:?]
	at com.AustinPilz.FridayThe13th.Listener.PlayerListener.onPlayerMove(PlayerListener.java:338) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	... 15 more`

**Comment by austinpilz** [comment]
Try updating to the [1.5 version](https://www.spigotmc.org/resources/friday-the-13th.43321/update?update=175988) I just posted.

Also - please keep in mind that the plugin is designed with the 1.12 API and therefore only supports 1.12. I am not sure if it supports 1.1.
