### ISSUE TITLE
task #61

### ISSUE THREAD

**Issue by XxELORDxX** [austinpilz/FridayThe13th#9]
[19:21:32 WARN]: [FridayThe13th] Task #61 for FridayThe13th v1.5.1 generated an
exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/Packet
        at com.AustinPilz.FridayThe13th.Components.Characters.Jason.<init>(Jason
.java:87) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.assignJason(
PlayerManager.java:693) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.assignGameRo
les(PlayerManager.java:660) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.performInPro
gressActions(PlayerManager.java:607) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.beginGame(Game
Manager.java:356) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.changeGameStat
us(GameManager.java:338) ~[?:?]
        at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.checkGameStatu
s(GameManager.java:245) ~[?:?]
        at com.AustinPilz.FridayThe13th.Runnable.GameStatusCheck.run(GameStatusC
heck.java:17) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
723) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.Packe
t
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        ... 15 more

**Comment by austinpilz** [comment]
You're running 1.10, only 1.12 is supported.
